export { applyEnvelope } from './envelope';
export { createImpulse, createSoftClipCurve } from './fx/reverb';
export { CHIP_KIT, DrumKit, LOFI_KIT, type DrumKitDefinition } from './instruments/drums';
export { FmInstrument } from './instruments/fm';
export { PadInstrument } from './instruments/pad';
export { TonalInstrument } from './instruments/tonal';
export type { Instrument } from './instruments/types';
export { createCrackleBuffer, createNoiseBuffer } from './noise';
export { analyze, encodeWav, renderOffline } from './offline';
export type { OfflineRenderOptions, RenderStats } from './offline';
export { Renderer } from './renderer';
export { LookaheadScheduler } from './scheduler';
export type { SchedulerOptions } from './scheduler';
export { WaveTable } from './waves';
