import type { Style } from './schema';

/**
 * Slow and spacious: drones, long pads, sparse pentatonic bells and deep
 * reverb, with soft percussion only sometimes. Slow sensors shape it most.
 */
export const ambient: Style = {
  id: 'ambient',
  name: 'Ambient',
  description: 'Drones under slow pads, sparse bells and deep reverb.',
  defaultTempo: 72,
  palette: {
    modes: ['aeolian', 'dorian', 'mixolydian', 'ionian', 'lydian'],
    progression: {
      0: { 3: 3, 5: 3, 1: 1, 2: 1, 4: 1 },
      1: { 4: 2, 3: 2, 0: 1 },
      2: { 5: 3, 3: 2 },
      3: { 0: 4, 5: 2, 1: 1 },
      4: { 0: 3, 5: 2, 3: 2 },
      5: { 3: 3, 0: 2, 1: 1, 2: 1 },
      6: { 0: 3, 5: 1 },
    },
    chordRates: [2, 2, 4, 1],
    chordSize: [3, 5],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.5, 0.54],
    trackCount: [4, 6],
    slots: [
      { role: 'drone', machines: ['drone', 'hollow'], required: true },
      { role: 'pad', machines: ['pad', 'glass'], required: true },
      { role: 'arp', machines: ['pluck'], weight: 2 },
      { role: 'drum', machines: ['rim', 'shaker'], weight: 1.5 },
      { role: 'drum', machines: ['heart'], weight: 0.8 },
      { role: 'lead', machines: ['bell', 'chime'], required: true },
      { role: 'lead', machines: ['chime', 'flute'], weight: 1 },
    ],
    machines: {
      drone: {
        label: 'Saw drone',
        role: 'drone',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.2,
          voices: 3,
          detune: 14,
          cutoff: [260, 1600],
          env: { a: 3, d: 2, s: 0.85, r: 4 },
          gate: 1,
        },
        range: [36, 50],
        fifth: true,
        density: [0.02, 0.02],
        lengths: [64],
        scales: [0.5, 1],
        filter: [200, 8000],
        base: { attack: [0.5, 0.8], sendReverb: [0.4, 0.7], cutoff: [0.45, 0.8] },
      },
      hollow: {
        label: 'Hollow drone',
        role: 'drone',
        patch: {
          type: 'pad',
          wave: 'triangle',
          gain: 0.3,
          voices: 2,
          detune: 8,
          cutoff: [400, 2400],
          env: { a: 4, d: 2, s: 0.9, r: 5 },
          gate: 1,
        },
        range: [38, 55],
        fifth: false,
        density: [0.02, 0.02],
        lengths: [64],
        scales: [0.5, 1],
        base: { sendReverb: [0.5, 0.8] },
      },
      pad: {
        label: 'Saw pad',
        role: 'pad',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.11,
          voices: 3,
          detune: 10,
          cutoff: [500, 3000],
          env: { a: 1.8, d: 1.5, s: 0.7, r: 2.5 },
          gate: 1,
        },
        range: [52, 74],
        density: [0.03, 0.08],
        lengths: [32, 64, 48, 24],
        scales: [0.5, 0.75, 1],
        base: { attack: [0.5, 0.85], sendReverb: [0.4, 0.8] },
      },
      glass: {
        label: 'Glass pad',
        role: 'pad',
        patch: {
          type: 'pad',
          wave: 'triangle',
          gain: 0.16,
          voices: 4,
          detune: 16,
          cutoff: [900, 5000],
          env: { a: 2.5, d: 2, s: 0.6, r: 3 },
          gate: 1,
        },
        range: [55, 79],
        density: [0.03, 0.08],
        lengths: [32, 48, 64, 40],
        scales: [0.5, 0.75],
        base: { sendReverb: [0.5, 0.85], sendDelay: [0.1, 0.35] },
      },
      bell: {
        label: 'FM bell',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.17,
          ratio: 3.5,
          index: [4, 0.3],
          indexDecay: 1.2,
          env: { a: 0.005, d: 2.5, s: 0, r: 1.5 },
        },
        range: [69, 93],
        pentatonic: true,
        density: [0.04, 0.2],
        lengths: [16, 24, 32, 20, 28, 12, 36],
        scales: [0.5, 0.75, 1],
        maxLen: 12,
        base: { sendReverb: [0.35, 0.7], sendDelay: [0.2, 0.5] },
      },
      chime: {
        label: 'Glass chime',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.11,
          ratio: 5,
          index: [2.5, 0.2],
          indexDecay: 0.8,
          env: { a: 0.003, d: 1.8, s: 0, r: 1.2 },
        },
        range: [72, 96],
        pentatonic: true,
        density: [0.03, 0.15],
        lengths: [20, 28, 12, 36, 44, 9, 11],
        scales: [0.5, 0.75, 1],
        maxLen: 8,
        base: { sendReverb: [0.45, 0.8], sendDelay: [0.25, 0.6], pan: [0.15, 0.85] },
      },
      flute: {
        label: 'Breath flute',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.14,
          env: { a: 0.25, d: 0.6, s: 0.7, r: 0.8 },
          gate: 0.95,
          detune: 6,
          vibrato: { rate: 4.2, depth: 12, delay: 0.4 },
        },
        range: [62, 86],
        pentatonic: true,
        density: [0.04, 0.16],
        lengths: [16, 24, 32, 20],
        scales: [0.5, 0.75],
        maxLen: 12,
        base: { sendReverb: [0.4, 0.7], sendDelay: [0.1, 0.4] },
      },
      pluck: {
        label: 'Soft pluck',
        role: 'arp',
        patch: {
          type: 'fm',
          gain: 0.09,
          ratio: 2,
          index: [1.6, 0.2],
          indexDecay: 0.3,
          env: { a: 0.004, d: 0.9, s: 0, r: 0.6 },
        },
        range: [60, 84],
        density: [0.1, 0.35],
        lengths: [12, 16, 10, 14, 9],
        scales: [0.5, 0.75, 1],
        base: { sendReverb: [0.35, 0.65], sendDelay: [0.2, 0.55] },
      },
      rim: {
        label: 'Soft rim',
        role: 'drum',
        patch: { type: 'drum', voice: 'rim', flavor: 'soft', gain: 0.22 },
        density: [0.05, 0.25],
        lengths: [16, 12, 10, 7],
        scales: [0.5, 1],
        base: { sendReverb: [0.3, 0.6] },
      },
      shaker: {
        label: 'Shaker',
        role: 'drum',
        patch: { type: 'drum', voice: 'shaker', flavor: 'soft', gain: 0.16 },
        density: [0.1, 0.4],
        lengths: [16, 12, 8, 6],
        scales: [0.5, 1],
        base: { sendReverb: [0.2, 0.5], pan: [0.2, 0.8] },
      },
      heart: {
        label: 'Heartbeat',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'soft', gain: 0.3 },
        density: [0.04, 0.12],
        lengths: [16, 32],
        scales: [0.5, 1],
        base: { cutoff: [0.4, 0.7], sendReverb: [0.2, 0.45] },
      },
    },
    lengths: [16, 24, 32, 20, 28, 12],
    scales: [0.5, 0.75, 1, 1],
    lfoPeriod: [32, 512],
    maxEventsPerStep: 12,
  },
  fx: {
    reverb: [0.25, 0.6],
    reverbSeconds: 5.5,
    delay: [0.1, 0.4],
    delaySteps: 6,
    filter: [1200, 9000],
  },
};
