import type { Style } from './schema';

/**
 * Blues: a shuffle over the 12-bar form (major, quick-change or minor),
 * walking bass, organ and piano, and leads that bend to blue notes.
 */
export const blues: Style = {
  id: 'blues',
  name: 'Blues',
  description: '12-bar shuffle, walking bass, organ and a lead that bends to blue notes.',
  defaultTempo: 96,
  palette: {
    modes: ['mixolydian'],
    progression: { 0: { 0: 1 } },
    chordScales: {
      keyLabel: 'blues',
      chords: [
        { id: 'I7', root: 0, mode: 'mixolydian' },
        { id: 'IV7', root: 5, mode: 'mixolydian' },
        { id: 'V7', root: 7, mode: 'mixolydian' },
        { id: 'i7', root: 0, mode: 'dorian' },
        { id: 'iv7', root: 5, mode: 'dorian' },
        { id: '♭VI7', root: 8, mode: 'lydianDominant' },
        { id: 'V7♭9', root: 7, mode: 'phrygianDominant' },
      ],
      forms: [
        {
          id: 'minor',
          label: 'Minor 12-bar',
          brightness: 0.2,
          sequence: [
            'i7',
            'i7',
            'i7',
            'i7',
            'iv7',
            'iv7',
            'i7',
            'i7',
            '♭VI7',
            'V7♭9',
            'i7',
            'V7♭9',
          ],
        },
        {
          id: 'major',
          label: '12-bar',
          brightness: 0.6,
          sequence: ['I7', 'I7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'I7', 'V7', 'IV7', 'I7', 'V7'],
        },
        {
          id: 'quick',
          label: 'Quick-change 12-bar',
          brightness: 0.85,
          sequence: ['I7', 'IV7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'I7', 'V7', 'IV7', 'I7', 'V7'],
        },
      ],
    },
    chordRates: [1],
    chordSize: [4, 4],
    phraseBars: 4,
    sectionBars: 24,
    swing: [0.63, 0.67],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['snare'], required: true },
      { role: 'drum', machines: ['hat', 'ride'], required: true },
      { role: 'bass', machines: ['walking'], required: true },
      { role: 'chords', machines: ['organ', 'piano'], required: true },
      { role: 'lead', machines: ['harp', 'guitar'], required: true },
      { role: 'chords', machines: ['piano'], weight: 1 },
    ],
    machines: {
      kick: {
        label: 'Kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'lofi', gain: 0.34 },
        density: [0.12, 0.25],
        lengths: [16],
        base: { pan: [0.5, 0.5] },
      },
      snare: {
        label: 'Shuffle snare',
        role: 'drum',
        patch: { type: 'drum', voice: 'snare', flavor: 'lofi', gain: 0.34 },
        rhythm: 'backbeat',
        density: [0.12, 0.25],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.35] },
      },
      hat: {
        label: 'Shuffle hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'lofi', gain: 0.18 },
        rhythm: 'pulse',
        density: [0.5, 0.5],
        lengths: [16],
      },
      ride: {
        label: 'Ride',
        role: 'drum',
        patch: { type: 'drum', voice: 'ride', flavor: 'lofi', gain: 0.24 },
        rhythm: 'ride',
        density: [0.4, 0.4],
        lengths: [16],
      },
      walking: {
        label: 'Walking bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'triangle',
          gain: 0.4,
          env: { a: 0.006, d: 0.3, s: 0.5, r: 0.1 },
          gate: 0.9,
          detune: 4,
        },
        rhythm: 'walking',
        range: [28, 50],
        density: [0.25, 0.25],
        lengths: [16],
        filter: [80, 4000],
        base: { cutoff: [0.45, 0.7], pan: [0.5, 0.5] },
      },
      organ: {
        label: 'Drawbar organ',
        role: 'chords',
        patch: {
          type: 'organ',
          gain: 0.06,
          drawbars: [0.8, 0.8, 1, 0.6, 0, 0.3, 0, 0, 0.2],
          env: { a: 0.01, d: 0.2, s: 0.9, r: 0.08 },
          gate: 0.9,
          tremolo: { rate: 6, depth: 0.3 },
        },
        rhythm: 'charleston',
        range: [52, 74],
        density: [0.1, 0.3],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.35], pan: [0.35, 0.65] },
      },
      piano: {
        label: 'Barrelhouse piano',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.07,
          ratio: 1,
          index: [1.8, 0.35],
          indexDecay: 0.3,
          env: { a: 0.003, d: 1.2, s: 0.15, r: 0.4 },
          gate: 0.8,
        },
        rhythm: 'offbeat',
        range: [55, 77],
        density: [0.25, 0.3],
        lengths: [16],
        base: { pan: [0.55, 0.75], sendReverb: [0.1, 0.3] },
      },
      harp: {
        label: 'Harmonica',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sawtooth',
          gain: 0.08,
          env: { a: 0.03, d: 0.25, s: 0.7, r: 0.12 },
          gate: 0.9,
          vibrato: { rate: 6, depth: 25, delay: 0.15 },
          filter: { range: [700, 3500], q: 3, env: 0.3, decay: 0.2 },
          glide: { time: 0.05 },
        },
        range: [64, 86],
        blueNotes: true,
        slide: 0.25,
        density: [0.1, 0.35],
        lengths: [16, 32],
        maxLen: 6,
        base: { sendReverb: [0.15, 0.35] },
      },
      guitar: {
        label: 'Electric guitar',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.09,
          ratio: 1,
          index: [3, 0.8],
          indexDecay: 0.25,
          env: { a: 0.003, d: 0.8, s: 0.35, r: 0.25 },
          vibrato: { rate: 5.5, depth: 20, delay: 0.3 },
        },
        range: [59, 84],
        blueNotes: true,
        density: [0.1, 0.35],
        lengths: [16, 32],
        maxLen: 6,
        base: { drive: [0.2, 0.5], sendReverb: [0.15, 0.35], sendDelay: [0.05, 0.2] },
      },
    },
    lengths: [16, 32],
    scales: [1],
    lfoPeriod: [32, 512],
    maxEventsPerStep: 12,
  },
  fx: {
    reverb: [0.08, 0.25],
    reverbSeconds: 2,
    delay: [0, 0.1],
    delaySteps: 3,
    filter: [2000, 10000],
    humanize: 8,
  },
};
