import type { Style } from './schema';

/**
 * Drum & bass: breakbeats with ghost notes and rolls, a deep reese bass over
 * a clean sub, and atmospheric pads. The tempo you set is the drums'; the
 * pads and bass move at half that.
 */
export const dnb: Style = {
  id: 'dnb',
  name: 'Drum & bass',
  description: 'Fast breakbeats with rolls, a deep reese bass, a sub and atmospheric pads.',
  defaultTempo: 172,
  palette: {
    modes: ['phrygian', 'aeolian', 'dorian'],
    progression: {
      0: { 5: 3, 3: 2, 6: 1 },
      1: { 0: 2, 4: 1 },
      2: { 5: 2, 3: 1 },
      3: { 0: 3, 5: 1 },
      4: { 0: 3 },
      5: { 3: 2, 0: 2, 6: 1 },
      6: { 0: 3 },
    },
    chordRates: [2, 4],
    chordSize: [3, 4],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.5, 0.55],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['snare'], required: true },
      { role: 'drum', machines: ['hat', 'ride'], required: true },
      { role: 'drum', machines: ['shaker', 'perc'], weight: 1 },
      { role: 'bass', machines: ['reese'], required: true },
      { role: 'bass', machines: ['sub'], weight: 2 },
      { role: 'pad', machines: ['atmos'], weight: 2 },
      { role: 'lead', machines: ['bell'], weight: 1 },
    ],
    machines: {
      kick: {
        label: 'Break kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'lofi', gain: 0.42 },
        rhythm: 'break',
        density: [0.12, 0.18],
        lengths: [32, 16],
        base: { cutoff: [0.85, 1], drive: [0.1, 0.35], pan: [0.5, 0.5] },
      },
      snare: {
        label: 'Break snare',
        role: 'drum',
        patch: { type: 'drum', voice: 'snare', flavor: 'lofi', gain: 0.4 },
        rhythm: 'break',
        density: [0.12, 0.3],
        lengths: [32, 16],
        base: { tune: [0.55, 0.8], sendReverb: [0.05, 0.25] },
      },
      hat: {
        label: 'Break hats',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'lofi', gain: 0.2 },
        density: [0.4, 0.85],
        lengths: [16, 32, 12],
        base: { retrig: [0.5, 0.85], pan: [0.35, 0.65] },
      },
      ride: {
        label: 'Ride',
        role: 'drum',
        patch: { type: 'drum', voice: 'ride', flavor: 'lofi', gain: 0.18 },
        rhythm: 'pulse',
        density: [0.5, 0.5],
        lengths: [16],
      },
      shaker: {
        label: 'Shaker',
        role: 'drum',
        patch: { type: 'drum', voice: 'shaker', flavor: 'lofi', gain: 0.14 },
        density: [0.4, 0.9],
        lengths: [16, 12],
      },
      perc: {
        label: 'Perc',
        role: 'drum',
        patch: { type: 'drum', voice: 'perc', flavor: 'lofi', gain: 0.16 },
        density: [0.08, 0.25],
        lengths: [7, 11, 13],
        base: { sendDelay: [0.2, 0.5], pan: [0.15, 0.85] },
      },
      reese: {
        label: 'Reese bass',
        role: 'bass',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.16,
          voices: 3,
          detune: 28,
          cutoff: [180, 1600],
          env: { a: 0.02, d: 0.6, s: 0.85, r: 0.2 },
          gate: 0.95,
        },
        range: [30, 47],
        density: [0.05, 0.15],
        lengths: [32, 16],
        maxLen: 16,
        filter: [80, 5000],
        base: { drive: [0.2, 0.55], cutoff: [0.35, 0.7], pan: [0.5, 0.5] },
      },
      sub: {
        label: 'Sub',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.38,
          env: { a: 0.005, d: 0.3, s: 0.85, r: 0.1 },
          gate: 0.95,
        },
        range: [28, 40],
        density: [0.05, 0.12],
        lengths: [32],
        maxLen: 16,
        base: { pan: [0.5, 0.5], sendReverb: [0, 0.03] },
      },
      atmos: {
        label: 'Atmosphere',
        role: 'pad',
        patch: {
          type: 'pad',
          wave: 'triangle',
          gain: 0.12,
          voices: 4,
          detune: 18,
          cutoff: [700, 4500],
          env: { a: 2.5, d: 2, s: 0.7, r: 3 },
          gate: 1,
        },
        range: [55, 79],
        density: [0.03, 0.06],
        lengths: [64, 32],
        scales: [0.5, 1],
        base: { sendReverb: [0.5, 0.85], sendDelay: [0.1, 0.35] },
      },
      bell: {
        label: 'Bell',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.08,
          ratio: 3.5,
          index: [3, 0.2],
          indexDecay: 0.8,
          env: { a: 0.004, d: 1.8, s: 0, r: 1 },
        },
        range: [72, 93],
        pentatonic: true,
        density: [0.03, 0.12],
        lengths: [32, 16, 24],
        scales: [0.5, 1],
        maxLen: 8,
        base: { sendReverb: [0.4, 0.75], sendDelay: [0.25, 0.55] },
      },
    },
    lengths: [32, 16, 32],
    scales: [1, 1, 0.5],
    lfoPeriod: [16, 512],
    maxEventsPerStep: 12,
  },
  fx: {
    reverb: [0.08, 0.3],
    reverbSeconds: 3.2,
    delay: [0.05, 0.25],
    delaySteps: 6,
    filter: [1800, 15000],
  },
};
