import type { Style } from './schema';

/**
 * Hip-hop: hard kicks and snares, rolling hats, an 808 that slides, dusty
 * keys or strings, and hooks that bend to blue notes.
 */
export const hiphop: Style = {
  id: 'hiphop',
  name: 'Hip-hop',
  description: 'Hard drums, rolling hats, a sliding 808, dusty keys and blue-note hooks.',
  defaultTempo: 90,
  palette: {
    modes: ['phrygian', 'aeolian', 'dorian'],
    progression: {
      0: { 5: 3, 3: 3, 6: 1, 4: 1 },
      1: { 4: 3, 0: 2 },
      2: { 5: 2, 3: 2 },
      3: { 0: 3, 4: 2, 5: 1 },
      4: { 0: 4, 5: 1 },
      5: { 3: 3, 6: 2, 0: 2 },
      6: { 0: 3, 5: 1 },
    },
    chordRates: [2, 1, 4],
    chordSize: [3, 4],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.52, 0.6],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['snare', 'clap'], required: true },
      { role: 'drum', machines: ['hat'], required: true },
      { role: 'drum', machines: ['ohat', 'perc', 'rim'], weight: 1.5 },
      { role: 'bass', machines: ['eight08'], required: true },
      { role: 'chords', machines: ['keys', 'strings'], weight: 2 },
      { role: 'lead', machines: ['pluck', 'flute'], weight: 2 },
    ],
    machines: {
      kick: {
        label: 'Hard kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'lofi', gain: 0.46 },
        density: [0.12, 0.3],
        lengths: [16, 32],
        base: { cutoff: [0.85, 1], drive: [0.15, 0.45], sendReverb: [0, 0.06], pan: [0.5, 0.5] },
      },
      snare: {
        label: 'Crack snare',
        role: 'drum',
        patch: { type: 'drum', voice: 'snare', flavor: 'lofi', gain: 0.42 },
        rhythm: 'backbeat',
        density: [0.08, 0.18],
        lengths: [16, 32],
        base: { tune: [0.55, 0.8], sendReverb: [0.1, 0.3] },
      },
      clap: {
        label: 'Clap',
        role: 'drum',
        patch: { type: 'drum', voice: 'clap', flavor: 'lofi', gain: 0.36 },
        rhythm: 'backbeat',
        density: [0.08, 0.18],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.4] },
      },
      hat: {
        label: 'Rolling hats',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'chip', gain: 0.22 },
        density: [0.4, 0.9],
        lengths: [16, 8, 12],
        scales: [1, 2],
        base: { retrig: [0.6, 0.95], pan: [0.35, 0.65], cutoff: [0.7, 1] },
      },
      ohat: {
        label: 'Open hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'ohat', flavor: 'lofi', gain: 0.2 },
        rhythm: 'offbeat',
        density: [0.05, 0.2],
        lengths: [16, 32],
      },
      perc: {
        label: 'Perc',
        role: 'drum',
        patch: { type: 'drum', voice: 'perc', flavor: 'chip', gain: 0.2 },
        density: [0.05, 0.2],
        lengths: [12, 7, 10, 16],
        base: { pan: [0.15, 0.85], sendDelay: [0.15, 0.45] },
      },
      rim: {
        label: 'Rim',
        role: 'drum',
        patch: { type: 'drum', voice: 'rim', flavor: 'lofi', gain: 0.24 },
        density: [0.05, 0.18],
        lengths: [16, 12, 7],
      },
      eight08: {
        label: '808',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.5,
          env: { a: 0.003, d: 0.7, s: 0.7, r: 0.18 },
          gate: 0.95,
          glide: { time: 0.09 },
          pitchEnv: { semitones: 7, time: 0.04 },
        },
        range: [28, 48],
        slide: 0.25,
        density: [0.1, 0.3],
        lengths: [16, 32],
        maxLen: 8,
        filter: [80, 6000],
        base: { drive: [0.2, 0.5], sendReverb: [0, 0.04], pan: [0.5, 0.5] },
      },
      keys: {
        label: 'Dusty keys',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.08,
          ratio: 1,
          index: [1.8, 0.5],
          indexDecay: 0.5,
          env: { a: 0.004, d: 1.4, s: 0.3, r: 0.5 },
          gate: 0.95,
        },
        range: [52, 74],
        density: [0.05, 0.15],
        lengths: [16, 32],
        base: { cutoff: [0.45, 0.75], sendReverb: [0.15, 0.4] },
      },
      strings: {
        label: 'Strings',
        role: 'chords',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.08,
          voices: 4,
          detune: 14,
          cutoff: [500, 3000],
          env: { a: 0.4, d: 1, s: 0.7, r: 0.8 },
          gate: 1,
        },
        range: [55, 79],
        density: [0.03, 0.08],
        lengths: [32, 16],
        base: { sendReverb: [0.25, 0.5] },
      },
      pluck: {
        label: 'Bell pluck',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.08,
          ratio: 3,
          index: [2, 0.2],
          indexDecay: 0.2,
          env: { a: 0.003, d: 0.6, s: 0, r: 0.3 },
        },
        range: [64, 86],
        blueNotes: true,
        density: [0.08, 0.3],
        lengths: [16, 32, 12],
        maxLen: 4,
        base: { sendDelay: [0.15, 0.45] },
      },
      flute: {
        label: 'Flute hook',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.11,
          env: { a: 0.05, d: 0.3, s: 0.7, r: 0.2 },
          gate: 0.9,
          detune: 5,
          vibrato: { rate: 5, depth: 14, delay: 0.15 },
        },
        range: [67, 88],
        blueNotes: true,
        density: [0.06, 0.22],
        lengths: [16, 32],
        maxLen: 6,
        base: { sendReverb: [0.15, 0.35], sendDelay: [0.1, 0.3] },
      },
    },
    lengths: [16, 32, 16, 24],
    scales: [1, 1, 1, 0.5],
    lfoPeriod: [16, 256],
    maxEventsPerStep: 12,
    effects: ['brake', 'tapeStop', 'stutter', 'dubThrow', 'dive', 'crush', 'wash'],
  },
  fx: {
    reverb: [0.04, 0.2],
    delay: [0.03, 0.22],
    delaySteps: 3,
    filter: [1500, 11000],
    crackle: [0.004, 0.018],
    humanize: 5,
  },
};
