import type { Style } from './schema';

/**
 * Jazz: swung ride, brushes and hi-hat on 2 and 4, a walking bass, rootless
 * comping, and a vibraphone or tenor line. Chords leave the key: secondary
 * dominants, minor ii–V–i, tritone substitutes, each over its own scale.
 */
export const jazz: Style = {
  id: 'jazz',
  name: 'Jazz',
  description:
    'Swung ride and brushes, walking bass, comping piano, vibraphone; ii–V–I and turnarounds.',
  defaultTempo: 132,
  palette: {
    modes: ['ionian'],
    progression: { 0: { 0: 1 } },
    chordScales: {
      keyLabel: 'jazz',
      chords: [
        { id: 'Imaj7', root: 0, mode: 'ionian' },
        { id: 'ii7', root: 2, mode: 'dorian' },
        { id: 'iii7', root: 4, mode: 'phrygian' },
        { id: 'IVmaj7', root: 5, mode: 'lydian' },
        { id: 'V7', root: 7, mode: 'mixolydian' },
        { id: 'vi7', root: 9, mode: 'aeolian' },
        { id: 'VI7', root: 9, mode: 'phrygianDominant' },
        { id: 'II7', root: 2, mode: 'mixolydian' },
        { id: '♭II7', root: 1, mode: 'lydianDominant' },
        { id: 'iv7', root: 5, mode: 'dorian' },
        { id: '♭VII7', root: 10, mode: 'mixolydian' },
        { id: 'i7', root: 0, mode: 'dorian' },
        { id: 'ii∅', root: 2, mode: 'locrian' },
        { id: 'V7♭9', root: 7, mode: 'phrygianDominant' },
        { id: '♭VImaj7', root: 8, mode: 'lydian' },
      ],
      forms: [
        {
          id: 'minor',
          label: 'Minor ii–V–i',
          brightness: 0.1,
          sequence: ['ii∅', 'V7♭9', 'i7', 'i7', 'iv7', '♭VImaj7', 'ii∅', 'V7♭9'],
        },
        {
          id: 'turnaround',
          label: 'iii–VI–ii–V',
          brightness: 0.4,
          sequence: ['Imaj7', 'vi7', 'ii7', 'V7', 'iii7', 'VI7', 'ii7', 'V7'],
        },
        {
          id: 'rhythm',
          label: 'I–VI–ii–V',
          brightness: 0.6,
          sequence: ['Imaj7', 'VI7', 'ii7', 'V7'],
        },
        {
          id: 'twofive',
          label: 'ii–V–I',
          brightness: 0.75,
          sequence: ['ii7', 'V7', 'Imaj7', 'Imaj7', 'II7', 'II7', 'ii7', 'V7'],
        },
        {
          id: 'backdoor',
          label: 'Back door',
          brightness: 0.95,
          sequence: ['Imaj7', 'Imaj7', 'IVmaj7', 'iv7', '♭VII7', '♭VII7', 'Imaj7', 'V7'],
        },
      ],
      substitutions: { V7: ['♭II7'], VI7: ['vi7'] },
    },
    chordRates: [1, 1, 0.5, 2],
    chordSize: [4, 5],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.62, 0.67],
    trackCount: [4, 6],
    slots: [
      { role: 'drum', machines: ['ride'], required: true },
      { role: 'drum', machines: ['brush', 'pedal'], weight: 3 },
      { role: 'drum', machines: ['kick'], weight: 1 },
      { role: 'bass', machines: ['upright'], required: true },
      { role: 'chords', machines: ['piano', 'rhodes'], required: true },
      { role: 'lead', machines: ['vibes', 'tenor'], weight: 3 },
    ],
    machines: {
      ride: {
        label: 'Ride',
        role: 'drum',
        patch: { type: 'drum', voice: 'ride', flavor: 'soft', gain: 0.3 },
        rhythm: 'ride',
        density: [0.4, 0.4],
        lengths: [16],
        base: { pan: [0.55, 0.7], sendReverb: [0.15, 0.3] },
      },
      brush: {
        label: 'Brushes',
        role: 'drum',
        patch: { type: 'drum', voice: 'brush', flavor: 'soft', gain: 0.24 },
        rhythm: 'backbeat',
        density: [0.12, 0.3],
        lengths: [16, 32],
        base: { pan: [0.4, 0.5], sendReverb: [0.15, 0.35] },
      },
      pedal: {
        label: 'Hi-hat on 2 and 4',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'soft', gain: 0.18 },
        rhythm: 'backbeat',
        density: [0.12, 0.12],
        lengths: [16],
        base: { decay: [0.3, 0.45], pan: [0.3, 0.45] },
      },
      kick: {
        label: 'Feathered kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'soft', gain: 0.22 },
        density: [0.04, 0.12],
        lengths: [16, 32],
        base: { pan: [0.5, 0.5] },
      },
      upright: {
        label: 'Walking bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'triangle',
          gain: 0.4,
          env: { a: 0.006, d: 0.35, s: 0.45, r: 0.1 },
          gate: 0.9,
          detune: 4,
        },
        rhythm: 'walking',
        range: [28, 50],
        density: [0.25, 0.25],
        lengths: [16, 32],
        filter: [80, 4000],
        base: { cutoff: [0.45, 0.7], pan: [0.45, 0.55], sendReverb: [0.05, 0.15] },
      },
      piano: {
        label: 'Comping piano',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.07,
          ratio: 1,
          index: [1.4, 0.3],
          indexDecay: 0.35,
          env: { a: 0.003, d: 1.6, s: 0.15, r: 0.5 },
          gate: 0.9,
        },
        rhythm: 'charleston',
        range: [52, 74],
        density: [0.1, 0.3],
        lengths: [16, 32],
        base: { pan: [0.55, 0.7], sendReverb: [0.15, 0.3] },
      },
      rhodes: {
        label: 'Rhodes',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.08,
          ratio: 1,
          index: [2.2, 0.6],
          indexDecay: 0.6,
          env: { a: 0.004, d: 1.4, s: 0.3, r: 0.5 },
          gate: 0.9,
          tremolo: { rate: 4.5, depth: 0.25 },
        },
        rhythm: 'charleston',
        range: [52, 74],
        density: [0.1, 0.3],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.35] },
      },
      vibes: {
        label: 'Vibraphone',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.1,
          ratio: 4,
          index: [1.6, 0.15],
          indexDecay: 0.25,
          env: { a: 0.002, d: 1.6, s: 0, r: 0.8 },
          tremolo: { rate: 5.5, depth: 0.35 },
        },
        range: [62, 86],
        density: [0.12, 0.4],
        lengths: [16, 32],
        maxLen: 4,
        base: { pan: [0.3, 0.45], sendReverb: [0.2, 0.4] },
      },
      tenor: {
        label: 'Tenor line',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sawtooth',
          gain: 0.08,
          env: { a: 0.03, d: 0.3, s: 0.65, r: 0.15 },
          gate: 0.9,
          vibrato: { rate: 5, depth: 12, delay: 0.25 },
          filter: { range: [500, 3200], q: 2, env: 0.35, decay: 0.25 },
        },
        range: [55, 79],
        density: [0.12, 0.4],
        lengths: [16, 32],
        maxLen: 6,
        base: { sendReverb: [0.15, 0.35] },
      },
    },
    lengths: [16, 32],
    scales: [1],
    lfoPeriod: [32, 512],
    maxEventsPerStep: 12,
    effects: ['wash', 'dubThrow', 'dive', 'sweep'],
  },
  fx: {
    reverb: [0.1, 0.3],
    reverbSeconds: 2.2,
    delay: [0, 0.08],
    delaySteps: 6,
    filter: [2500, 12000],
    humanize: 8,
  },
};
