import type { Style } from './schema';

/**
 * Lo-fi hip hop: swung boom-bap drums, electric-piano 7th and 9th chords,
 * a round sub bass, a sparse melody, vinyl crackle and tape wobble.
 */
export const lofi: Style = {
  id: 'lofi',
  name: 'Lo-fi',
  description: 'Dusty electric piano, round bass and lazy swung drums.',
  defaultTempo: 82,
  swing: 0.6,
  modes: ['aeolian', 'dorian', 'mixolydian', 'ionian'],
  progression: {
    0: { 3: 3, 1: 3, 5: 2, 2: 1 },
    1: { 4: 5, 3: 1, 6: 0.5 },
    2: { 5: 3, 1: 2 },
    3: { 4: 2, 1: 2, 0: 2, 2: 1 },
    4: { 0: 4, 5: 2, 2: 1 },
    5: { 1: 4, 3: 2, 4: 1 },
    6: { 0: 3, 2: 1 },
  },
  chordRateBars: 1,
  chordSize: [4, 5],
  phraseBars: 4,
  sectionBars: 16,
  parts: [
    {
      id: 'drums',
      role: 'drums',
      instrument: 'kit',
      voices: {
        kick: ['x.........x.....', 'x.........x.x...', 'x.....x...x.x...', 'x..x..x...x..x..'],
        snare: ['....x.......x...', '....x.......x...', '....x.......x..o', '....x..o....x.o.'],
        hat: ['x...x...x...x...', 'x.x.x.x.x.x.x.x.', 'x.xox.x.x.xox.x.', 'xoxxxoxxxoxxxoxx'],
      },
      fills: [{ snare: 'x.xx' }, { kick: 'x.x.', snare: '..x.' }, { hat: '....', snare: '.xx.' }],
      accentVoice: 'rim',
      ghostVoice: 'hat',
    },
    {
      id: 'bass',
      role: 'bass',
      instrument: 'sub',
      range: [33, 50],
      patterns: ['R-------........', 'R-----..R-......', 'R-----.5R-....a.', 'R--.R-.5R-.3..a.'],
    },
    {
      id: 'keys',
      role: 'chords',
      instrument: 'ep',
      range: [53, 74],
      patterns: ['x-------........', 'x-----....x-....', 'x--...x-..x--...', 'x-.x--..x-.x--..'],
    },
    {
      id: 'melody',
      role: 'melody',
      instrument: 'lead',
      range: [67, 86],
      density: [0.06, 0.3],
      syncopation: 0.6,
      maxDur: 6,
    },
  ],
  instruments: {
    ep: {
      type: 'fm',
      gain: 0.08,
      ratio: 1,
      index: [2.2, 0.6],
      indexDecay: 0.6,
      env: { a: 0.004, d: 1.2, s: 0.35, r: 0.4 },
      gate: 0.95,
    },
    sub: {
      type: 'osc',
      wave: 'sine',
      gain: 0.42,
      env: { a: 0.006, d: 0.2, s: 0.85, r: 0.08 },
      gate: 0.9,
    },
    lead: {
      type: 'fm',
      gain: 0.07,
      pan: 0.15,
      ratio: 2,
      index: [1.4, 0.4],
      indexDecay: 0.4,
      env: { a: 0.01, d: 0.6, s: 0.4, r: 0.3 },
      vibrato: { rate: 4.5, depth: 10, delay: 0.25 },
    },
    kit: { type: 'lofiDrums', gain: 0.38 },
  },
  macroRanges: { energy: [0.25, 0.85], brightness: [0, 0.7] },
  fx: {
    reverb: [0.05, 0.2],
    delay: [0, 0.12],
    delaySteps: 3,
    filter: [900, 5500],
    crackle: [0.012, 0.04],
    wobble: [4, 20],
    humanize: 12,
  },
};
