import type { Style } from './schema';

/**
 * Lo-fi hip hop: swung boom-bap drums, electric-piano 7th and 9th chords, a
 * round sub bass, vinyl crackle and tape wobble.
 */
export const lofi: Style = {
  id: 'lofi',
  name: 'Lo-fi',
  description: 'Dusty electric piano, round bass and lazy swung drums.',
  defaultTempo: 82,
  palette: {
    modes: ['aeolian', 'dorian', 'mixolydian', 'ionian'],
    progression: {
      0: { 3: 3, 1: 3, 5: 2, 2: 1 },
      1: { 4: 5, 3: 1, 6: 0.5 },
      2: { 5: 3, 1: 2 },
      3: { 4: 2, 1: 2, 0: 2, 2: 1 },
      4: { 0: 4, 5: 2, 2: 1 },
      5: { 1: 4, 3: 2, 4: 1 },
      6: { 0: 3, 2: 1 },
    },
    chordRates: [1, 1, 2, 0.5],
    chordSize: [4, 5],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.55, 0.64],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['snare', 'clap'], required: true },
      { role: 'drum', machines: ['hat', 'shaker'], required: true },
      { role: 'drum', machines: ['rim', 'shaker'], weight: 1.5 },
      { role: 'bass', machines: ['sub', 'fmBass'], required: true },
      { role: 'chords', machines: ['ep', 'dusty'], required: true },
      { role: 'arp', machines: ['pluck'], weight: 1 },
      { role: 'lead', machines: ['lead', 'whistle'], weight: 2 },
    ],
    machines: {
      kick: {
        label: 'Dusty kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'lofi', gain: 0.4 },
        density: [0.1, 0.3],
        lengths: [16, 32, 16],
        scales: [1, 1, 0.5],
        base: { cutoff: [0.75, 1], sendReverb: [0, 0.08], pan: [0.45, 0.55] },
      },
      snare: {
        label: 'Boom-bap snare',
        role: 'drum',
        patch: { type: 'drum', voice: 'snare', flavor: 'lofi', gain: 0.36 },
        density: [0.08, 0.2],
        lengths: [16, 32],
        base: { sendReverb: [0.08, 0.3], pan: [0.4, 0.6] },
      },
      clap: {
        label: 'Clap',
        role: 'drum',
        patch: { type: 'drum', voice: 'clap', flavor: 'lofi', gain: 0.3 },
        density: [0.08, 0.2],
        lengths: [16, 32],
        base: { sendReverb: [0.1, 0.35] },
      },
      hat: {
        label: 'Tape hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'lofi', gain: 0.26 },
        density: [0.25, 0.75],
        lengths: [16, 8, 12, 6],
        scales: [1, 1, 2],
        base: { cutoff: [0.6, 0.9], pan: [0.3, 0.7] },
      },
      shaker: {
        label: 'Shaker',
        role: 'drum',
        patch: { type: 'drum', voice: 'shaker', flavor: 'lofi', gain: 0.18 },
        density: [0.2, 0.6],
        lengths: [16, 12, 6, 10],
        base: { pan: [0.2, 0.8] },
      },
      rim: {
        label: 'Rim',
        role: 'drum',
        patch: { type: 'drum', voice: 'rim', flavor: 'lofi', gain: 0.24 },
        density: [0.05, 0.2],
        lengths: [16, 12, 7, 10],
        base: { sendReverb: [0.1, 0.35], pan: [0.25, 0.75] },
      },
      sub: {
        label: 'Sub bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.42,
          env: { a: 0.006, d: 0.2, s: 0.85, r: 0.08 },
          gate: 0.9,
        },
        range: [33, 50],
        density: [0.08, 0.3],
        lengths: [16, 32, 32],
        maxLen: 8,
        filter: [100, 8000],
        base: { sendReverb: [0, 0.05], sendDelay: [0, 0.03], pan: [0.5, 0.5] },
      },
      fmBass: {
        label: 'Round FM bass',
        role: 'bass',
        patch: {
          type: 'fm',
          gain: 0.3,
          ratio: 1,
          index: [1.2, 0.3],
          indexDecay: 0.25,
          env: { a: 0.005, d: 0.4, s: 0.6, r: 0.1 },
          gate: 0.85,
        },
        range: [33, 52],
        density: [0.1, 0.35],
        lengths: [16, 32, 24],
        maxLen: 6,
        filter: [80, 6000],
        base: { cutoff: [0.5, 0.85], sendReverb: [0, 0.06], pan: [0.5, 0.5] },
      },
      ep: {
        label: 'Electric piano',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.08,
          ratio: 1,
          index: [2.2, 0.6],
          indexDecay: 0.6,
          env: { a: 0.004, d: 1.2, s: 0.35, r: 0.4 },
          gate: 0.95,
        },
        range: [53, 74],
        density: [0.06, 0.2],
        lengths: [16, 32, 24],
        base: { sendReverb: [0.1, 0.35], sendDelay: [0, 0.2] },
      },
      dusty: {
        label: 'Dusty keys',
        role: 'chords',
        patch: {
          type: 'pad',
          wave: 'triangle',
          gain: 0.09,
          voices: 2,
          detune: 12,
          cutoff: [600, 3500],
          env: { a: 0.02, d: 0.8, s: 0.5, r: 0.5 },
          gate: 0.9,
        },
        range: [55, 76],
        density: [0.05, 0.16],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.4] },
      },
      pluck: {
        label: 'Kalimba',
        role: 'arp',
        patch: {
          type: 'fm',
          gain: 0.07,
          ratio: 3,
          index: [1.5, 0.1],
          indexDecay: 0.15,
          env: { a: 0.003, d: 0.5, s: 0, r: 0.3 },
        },
        range: [62, 86],
        density: [0.12, 0.4],
        lengths: [16, 12, 10, 6],
        scales: [1, 0.5, 0.75],
        base: { sendDelay: [0.15, 0.45], pan: [0.2, 0.8] },
      },
      lead: {
        label: 'Mellow lead',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.07,
          ratio: 2,
          index: [1.4, 0.4],
          indexDecay: 0.4,
          env: { a: 0.01, d: 0.6, s: 0.4, r: 0.3 },
          vibrato: { rate: 4.5, depth: 10, delay: 0.25 },
        },
        range: [67, 86],
        density: [0.06, 0.3],
        lengths: [16, 32, 24, 12, 20],
        maxLen: 6,
        base: { sendDelay: [0.1, 0.35] },
      },
      whistle: {
        label: 'Whistle',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.09,
          env: { a: 0.04, d: 0.3, s: 0.7, r: 0.2 },
          gate: 0.85,
          vibrato: { rate: 5, depth: 15, delay: 0.2 },
        },
        range: [70, 88],
        pentatonic: true,
        density: [0.05, 0.22],
        lengths: [16, 32, 20],
        maxLen: 8,
        base: { sendReverb: [0.15, 0.4], sendDelay: [0.15, 0.4] },
      },
    },
    lengths: [16, 16, 32, 12, 24],
    scales: [1, 1, 0.5, 0.75],
    lfoPeriod: [16, 384],
    maxEventsPerStep: 12,
    effects: ['tapeStop', 'brake', 'wash', 'dubThrow', 'dive', 'crush'],
  },
  fx: {
    reverb: [0.05, 0.25],
    delay: [0.02, 0.2],
    delaySteps: 3,
    filter: [900, 5500],
    crackle: [0.012, 0.04],
    wobble: [4, 20],
    humanize: 12,
  },
};
