import type { Style } from './schema';

/**
 * Minimal, after Steve Reich: short marimba and piano cells repeated on a
 * steady eighth-note pulse. Tracks have different lengths, and some run a
 * hair slower than the rest, so the cells drift apart and back together.
 */
export const minimal: Style = {
  id: 'minimal',
  name: 'Minimal',
  description: 'Marimba and piano cells on a steady pulse, drifting out of phase and back.',
  defaultTempo: 120,
  drift: { phase: 2.5, pattern: 0.8, machine: 0.1, harmony: 0.6, sound: 0.8 },
  palette: {
    modes: ['dorian', 'mixolydian', 'ionian', 'lydian'],
    progression: {
      0: { 3: 2, 5: 2, 4: 1 },
      1: { 4: 2, 0: 1 },
      2: { 5: 2, 3: 1 },
      3: { 0: 3, 1: 1 },
      4: { 0: 3, 5: 1 },
      5: { 3: 2, 1: 2 },
      6: { 0: 2 },
    },
    chordRates: [4, 2, 4],
    chordSize: [3, 4],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.5, 0.5],
    trackCount: [4, 6],
    slots: [
      { role: 'lead', machines: ['marimba'], required: true },
      { role: 'lead', machines: ['marimba', 'piano'], required: true },
      { role: 'chords', machines: ['pulse'], required: true },
      { role: 'lead', machines: ['piano', 'clarinet'], weight: 2 },
      { role: 'bass', machines: ['bass'], weight: 1.5 },
      { role: 'drum', machines: ['shaker'], weight: 0.8 },
    ],
    machines: {
      marimba: {
        label: 'Marimba',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.13,
          ratio: 4,
          index: [2.5, 0.1],
          indexDecay: 0.08,
          env: { a: 0.002, d: 0.55, s: 0, r: 0.25 },
        },
        rhythm: 'pulse',
        range: [57, 81],
        density: [0.5, 0.5],
        lengths: [12, 16, 10, 8, 11, 13],
        scales: [1, 1, 15 / 16, 31 / 32],
        base: { pan: [0.15, 0.85], sendReverb: [0.15, 0.35] },
      },
      piano: {
        label: 'Piano',
        role: 'lead',
        patch: {
          type: 'fm',
          gain: 0.09,
          ratio: 1,
          index: [1.2, 0.2],
          indexDecay: 0.4,
          env: { a: 0.003, d: 1.4, s: 0.1, r: 0.6 },
        },
        rhythm: 'pulse',
        range: [60, 84],
        density: [0.5, 0.5],
        lengths: [12, 9, 14, 16],
        scales: [1, 31 / 32],
        base: { pan: [0.2, 0.8], sendReverb: [0.2, 0.4] },
      },
      clarinet: {
        label: 'Clarinet',
        role: 'lead',
        patch: {
          type: 'pulse',
          gain: 0.07,
          duty: [0.5],
          env: { a: 0.08, d: 0.4, s: 0.7, r: 0.4 },
          gate: 0.95,
          filter: { range: [400, 2400], q: 1, env: 0.2, decay: 0.4 },
        },
        range: [55, 79],
        density: [0.08, 0.2],
        lengths: [32, 24, 20],
        maxLen: 12,
        base: { sendReverb: [0.25, 0.45] },
      },
      pulse: {
        label: 'Pulsing chords',
        role: 'chords',
        patch: {
          type: 'fm',
          gain: 0.05,
          ratio: 2,
          index: [1, 0.2],
          indexDecay: 0.2,
          env: { a: 0.01, d: 0.5, s: 0.2, r: 0.3 },
        },
        rhythm: 'pulse',
        range: [53, 74],
        density: [0.5, 0.5],
        lengths: [16],
        base: { sendReverb: [0.2, 0.4] },
      },
      bass: {
        label: 'Low drone bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sine',
          gain: 0.3,
          env: { a: 0.2, d: 1, s: 0.8, r: 1 },
          gate: 1,
        },
        range: [33, 50],
        density: [0.04, 0.08],
        lengths: [32, 64],
        maxLen: 16,
        base: { sendReverb: [0.2, 0.4] },
      },
      shaker: {
        label: 'Shaker pulse',
        role: 'drum',
        patch: { type: 'drum', voice: 'shaker', flavor: 'soft', gain: 0.12 },
        rhythm: 'pulse',
        density: [0.5, 0.5],
        lengths: [16, 12],
        base: { pan: [0.3, 0.7], sendReverb: [0.2, 0.4] },
      },
    },
    lengths: [12, 16, 10],
    scales: [1, 15 / 16],
    lfoPeriod: [64, 512],
    maxEventsPerStep: 12,
    effects: ['gate', 'dubThrow', 'wash', 'sweep', 'dive'],
  },
  fx: {
    reverb: [0.12, 0.35],
    reverbSeconds: 3,
    delay: [0, 0.1],
    delaySteps: 3,
    filter: [3000, 14000],
  },
};
