import type { Style } from './schema';

/**
 * Synthwave: 80s drum machine with a huge gated snare, driving eighth-note
 * saw bass, arpeggios, wide detuned pads and a gliding lead.
 */
export const synthwave: Style = {
  id: 'synthwave',
  name: 'Synthwave',
  description: 'Gated snare, driving saw bass, arpeggios, wide pads and a gliding lead.',
  defaultTempo: 104,
  palette: {
    modes: ['aeolian', 'dorian', 'ionian', 'lydian'],
    progression: {
      0: { 5: 3, 3: 3, 4: 2, 6: 1 },
      1: { 4: 3, 3: 1 },
      2: { 5: 2, 3: 2 },
      3: { 4: 3, 0: 2, 5: 1 },
      4: { 0: 3, 5: 2 },
      5: { 3: 3, 4: 2, 6: 1 },
      6: { 0: 2, 3: 1 },
    },
    chordRates: [1, 2, 2],
    chordSize: [3, 4],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.5, 0.53],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['snare'], required: true },
      { role: 'drum', machines: ['hat', 'tom'], weight: 2 },
      { role: 'bass', machines: ['sawbass'], required: true },
      { role: 'arp', machines: ['arp'], weight: 2 },
      { role: 'pad', machines: ['supersaw'], weight: 2 },
      { role: 'lead', machines: ['lead'], required: true },
    ],
    machines: {
      kick: {
        label: 'Drum machine kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'chip', gain: 0.4 },
        density: [0.12, 0.25],
        lengths: [16, 32],
        base: { cutoff: [0.85, 1], sendReverb: [0.05, 0.15], pan: [0.5, 0.5] },
      },
      snare: {
        label: 'Gated snare',
        role: 'drum',
        patch: { type: 'drum', voice: 'snare', flavor: 'lofi', gain: 0.4 },
        rhythm: 'backbeat',
        density: [0.12, 0.15],
        lengths: [16, 32],
        base: { sendReverb: [0.6, 0.9], decay: [0.55, 0.75], tune: [0.45, 0.65] },
      },
      hat: {
        label: 'Hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'chip', gain: 0.18 },
        rhythm: 'pulse',
        density: [0.5, 0.6],
        lengths: [16, 8],
        scales: [1, 2],
      },
      tom: {
        label: 'Syndrum tom',
        role: 'drum',
        patch: { type: 'drum', voice: 'tom', flavor: 'chip', gain: 0.26 },
        density: [0.04, 0.15],
        lengths: [16, 32],
        base: { sendReverb: [0.3, 0.6], tune: [0.3, 0.7] },
      },
      sawbass: {
        label: 'Saw bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sawtooth',
          gain: 0.18,
          env: { a: 0.003, d: 0.15, s: 0.6, r: 0.06 },
          gate: 0.7,
          filter: { range: [180, 3000], q: 3, env: 0.45, decay: 0.12 },
        },
        rhythm: 'pulse',
        range: [33, 52],
        density: [0.5, 0.5],
        lengths: [16],
        maxLen: 2,
        base: { pan: [0.5, 0.5], sendReverb: [0, 0.1] },
      },
      arp: {
        label: 'Arpeggio',
        role: 'arp',
        patch: {
          type: 'pulse',
          gain: 0.08,
          duty: [0.25, 0.5],
          env: { a: 0.002, d: 0.12, s: 0.3, r: 0.08 },
          gate: 0.6,
          filter: { range: [600, 6000], q: 2, env: 0.4, decay: 0.1 },
        },
        range: [60, 84],
        density: [0.5, 0.9],
        lengths: [16, 8, 12],
        scales: [1, 2],
        base: { sendDelay: [0.25, 0.55], pan: [0.25, 0.75] },
      },
      supersaw: {
        label: 'Supersaw pad',
        role: 'pad',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.07,
          voices: 6,
          detune: 26,
          cutoff: [600, 4000],
          env: { a: 0.8, d: 1.5, s: 0.75, r: 1.5 },
          gate: 1,
        },
        range: [52, 76],
        density: [0.03, 0.08],
        lengths: [32, 16],
        base: { sendReverb: [0.35, 0.65], sendDelay: [0.05, 0.2] },
      },
      lead: {
        label: 'Glide lead',
        role: 'lead',
        patch: {
          type: 'osc',
          wave: 'sawtooth',
          gain: 0.09,
          env: { a: 0.01, d: 0.3, s: 0.7, r: 0.25 },
          gate: 0.95,
          detune: 10,
          vibrato: { rate: 5.5, depth: 15, delay: 0.25 },
          glide: { time: 0.08 },
          filter: { range: [800, 7000], q: 1.5, env: 0.3, decay: 0.3 },
        },
        range: [64, 88],
        slide: 0.2,
        density: [0.08, 0.3],
        lengths: [16, 32],
        maxLen: 8,
        base: { sendDelay: [0.2, 0.45], sendReverb: [0.2, 0.4] },
      },
    },
    lengths: [16, 32, 16],
    scales: [1, 1, 0.5],
    lfoPeriod: [16, 384],
    maxEventsPerStep: 12,
    effects: ['sweep', 'wash', 'gate', 'dive', 'dubThrow', 'stutter', 'tapeStop'],
  },
  fx: {
    reverb: [0.1, 0.35],
    reverbSeconds: 3.5,
    delay: [0.06, 0.3],
    delaySteps: 3,
    filter: [2500, 16000],
    wobble: [0, 6],
  },
};
