import type { Style } from './schema';

/**
 * Techno: four on the floor, offbeat hats, a squelchy acid bass with accents
 * and slides, dub chord stabs into the delay, and percussion loops of odd
 * lengths that drift against the bar.
 */
export const techno: Style = {
  id: 'techno',
  name: 'Techno',
  description: 'Four on the floor, offbeat hats, squelchy acid bass and dub chord stabs.',
  defaultTempo: 128,
  palette: {
    modes: ['phrygian', 'aeolian', 'dorian'],
    progression: {
      0: { 0: 4, 5: 2, 3: 2, 6: 1 },
      1: { 0: 3 },
      2: { 0: 2, 5: 1 },
      3: { 0: 3, 5: 1 },
      4: { 0: 3 },
      5: { 0: 3, 3: 1 },
      6: { 0: 3 },
    },
    chordRates: [4, 2, 4],
    chordSize: [3, 3],
    phraseBars: 4,
    sectionBars: 16,
    swing: [0.5, 0.54],
    trackCount: [5, 7],
    slots: [
      { role: 'drum', machines: ['kick'], required: true },
      { role: 'drum', machines: ['ohat'], required: true },
      { role: 'drum', machines: ['clap', 'rim'], weight: 3 },
      { role: 'drum', machines: ['hat', 'shaker'], weight: 2 },
      { role: 'drum', machines: ['perc', 'cowbell'], weight: 1.5 },
      { role: 'bass', machines: ['acid', 'rumble'], required: true },
      { role: 'chords', machines: ['stab'], weight: 2 },
      { role: 'pad', machines: ['wash'], weight: 1 },
    ],
    machines: {
      kick: {
        label: 'Floor kick',
        role: 'drum',
        patch: { type: 'drum', voice: 'kick', flavor: 'lofi', gain: 0.5 },
        rhythm: 'four',
        density: [0.25, 0.3],
        lengths: [16],
        base: { cutoff: [0.85, 1], drive: [0.2, 0.5], tune: [0.4, 0.55], pan: [0.5, 0.5] },
      },
      ohat: {
        label: 'Offbeat hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'ohat', flavor: 'chip', gain: 0.2 },
        rhythm: 'offbeat',
        density: [0.25, 0.3],
        lengths: [16],
        base: { decay: [0.2, 0.5], cutoff: [0.75, 1] },
      },
      clap: {
        label: 'Clap',
        role: 'drum',
        patch: { type: 'drum', voice: 'clap', flavor: 'chip', gain: 0.3 },
        rhythm: 'backbeat',
        density: [0.12, 0.2],
        lengths: [16, 32],
        base: { sendReverb: [0.15, 0.4] },
      },
      rim: {
        label: 'Rim',
        role: 'drum',
        patch: { type: 'drum', voice: 'rim', flavor: 'chip', gain: 0.22 },
        density: [0.1, 0.3],
        lengths: [7, 11, 13, 5],
        base: { sendDelay: [0.2, 0.5], pan: [0.2, 0.8] },
      },
      hat: {
        label: 'Closed hat',
        role: 'drum',
        patch: { type: 'drum', voice: 'hat', flavor: 'chip', gain: 0.18 },
        density: [0.5, 1],
        lengths: [16, 12],
        base: { pan: [0.3, 0.7] },
      },
      shaker: {
        label: 'Shaker',
        role: 'drum',
        patch: { type: 'drum', voice: 'shaker', flavor: 'lofi', gain: 0.16 },
        density: [0.4, 0.9],
        lengths: [16, 12, 6],
      },
      perc: {
        label: 'Perc loop',
        role: 'drum',
        patch: { type: 'drum', voice: 'perc', flavor: 'chip', gain: 0.18 },
        density: [0.15, 0.4],
        lengths: [5, 7, 9, 11],
        base: { tune: [0.3, 0.8], sendDelay: [0.2, 0.5], pan: [0.15, 0.85] },
      },
      cowbell: {
        label: 'Cowbell',
        role: 'drum',
        patch: { type: 'drum', voice: 'cowbell', flavor: 'chip', gain: 0.14 },
        density: [0.08, 0.25],
        lengths: [7, 12, 16],
        base: { sendDelay: [0.2, 0.5] },
      },
      acid: {
        label: 'Acid bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'sawtooth',
          gain: 0.2,
          env: { a: 0.002, d: 0.2, s: 0.6, r: 0.05 },
          gate: 0.85,
          filter: { range: [140, 5200], q: 13, env: 0.75, decay: 0.16 },
          glide: { time: 0.06 },
        },
        range: [33, 52],
        slide: 0.3,
        density: [0.35, 0.8],
        lengths: [16, 12, 8],
        maxLen: 2,
        base: { drive: [0.15, 0.45], sendDelay: [0.05, 0.2], pan: [0.45, 0.55] },
      },
      rumble: {
        label: 'Rumble bass',
        role: 'bass',
        patch: {
          type: 'osc',
          wave: 'triangle',
          gain: 0.36,
          env: { a: 0.004, d: 0.18, s: 0.5, r: 0.08 },
          gate: 0.7,
        },
        rhythm: 'offbeat',
        range: [30, 45],
        density: [0.25, 0.3],
        lengths: [16],
        maxLen: 2,
        filter: [80, 3000],
        base: { cutoff: [0.4, 0.75], sendReverb: [0.1, 0.25] },
      },
      stab: {
        label: 'Dub stab',
        role: 'chords',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.07,
          voices: 2,
          detune: 10,
          cutoff: [500, 3500],
          env: { a: 0.004, d: 0.25, s: 0, r: 0.2 },
          gate: 0.5,
        },
        rhythm: 'offbeat',
        range: [50, 72],
        density: [0.1, 0.3],
        lengths: [16, 32, 12],
        base: { sendDelay: [0.45, 0.85], sendReverb: [0.2, 0.45], cutoff: [0.3, 0.6] },
      },
      wash: {
        label: 'Wash pad',
        role: 'pad',
        patch: {
          type: 'pad',
          wave: 'sawtooth',
          gain: 0.06,
          voices: 4,
          detune: 18,
          cutoff: [300, 2400],
          env: { a: 2, d: 2, s: 0.7, r: 3 },
          gate: 1,
        },
        range: [50, 74],
        density: [0.03, 0.06],
        lengths: [64, 32],
        base: { sendReverb: [0.4, 0.7], cutoff: [0.2, 0.5] },
      },
    },
    lengths: [16, 32, 16, 12],
    scales: [1, 1, 1, 0.5],
    lfoPeriod: [8, 256],
    maxEventsPerStep: 12,
  },
  fx: {
    reverb: [0.05, 0.25],
    delay: [0.06, 0.35],
    delaySteps: 3,
    filter: [1800, 16000],
  },
};
